version: '3'
services:
  database:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=huyak
    ports:
      - "5432:5432"
  api-server:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
    depends_on:
      - database
